function com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset(){var I='bootstrap',J='begin',K='gwt.codesvr.com.sibvisions.rad.ui.vaadin.ext.ui.Widgetset=',L='gwt.codesvr=',M='com.sibvisions.rad.ui.vaadin.ext.ui.Widgetset',N='startup',O='DUMMY',P=0,Q=1,R='iframe',S='javascript:""',T='position:absolute; width:0; height:0; border:none; left: -1000px;',U=' top: -1000px;',V='CSS1Compat',W='<!doctype html>',X='',Y='<html><head><\/head><body><\/body><\/html>',Z='undefined',$='readystatechange',_=10,ab='Chrome',bb='eval("',cb='");',db='script',eb='javascript',fb='moduleStartup',gb='moduleRequested',hb='com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset',ib='Failed to load ',jb='head',kb='meta',lb='name',mb='com.sibvisions.rad.ui.vaadin.ext.ui.Widgetset::',nb='::',ob='gwt:property',pb='content',qb='=',rb='gwt:onPropertyErrorFn',sb='Bad handler "',tb='" for "gwt:onPropertyErrorFn"',ub='gwt:onLoadErrorFn',vb='" for "gwt:onLoadErrorFn"',wb='#',xb='?',yb='/',zb='img',Ab='clear.cache.gif',Bb='baseUrl',Cb='com.sibvisions.rad.ui.vaadin.ext.ui.Widgetset.nocache.js',Db='base',Eb='//',Fb='modernie',Gb='MSIE',Hb='Trident',Ib='yes',Jb='none',Kb='selectingPermutation',Lb='com.sibvisions.rad.ui.vaadin.ext.ui.Widgetset.devmode.js',Mb='2EE645C43975718388C097EBEC77D321',Nb=':',Ob='.cache.js',Pb='loadExternalRefs',Qb='end';var o=window;var p=document;r(I,J);function q(){var a=o.location.search;return a.indexOf(K)!=-1||a.indexOf(L)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:M,sessionId:o.__gwtStatsSessionId,subSystem:N,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__sendStats=r;com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__moduleName=M;com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__errFn=null;com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__moduleBase=O;com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__softPermutationId=P;com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__computePropValue=null;com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__getPropMap=null;com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__installRunAsyncCode=function(){};com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__gwtStartLoadingFragment=function(){return null};com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__gwt_isKnownPropertyValue=function(){return false};com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[M]={moduleName:M};com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__moduleStartupDone=function(e){var f=t[M].bindings;t[M].bindings=function(){var a=f?f():{};var b=e[com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__softPermutationId];for(var c=P;c<b.length;c++){var d=b[c];a[d[P]]=d[Q]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(R);a.src=S;a.id=M;a.style.cssText=T+U;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==V?W:X;u.write(b+Y);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==Z){return typeof p.body!=Z&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(p.removeEventListener){p.removeEventListener($,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener($,d,false)}var e=setInterval(function(){d()},_)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(ab)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(bb));for(var i=P;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Q,j.length-Q)))}h.appendChild(e.createTextNode(cb));g=e.createElement(db);g.language=eb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=P;i<c.length;i++){g=e.createElement(db);g.language=eb;g.text=c[i];f.appendChild(g);d(f,g)}}}
com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.onScriptDownloaded=function(a){l(function(){m(a)})};r(fb,gb);var n=p.createElement(db);n.src=k;if(com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__errFn){n.onerror=function(){com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__errFn(hb,new Error(ib+code))}}p.getElementsByTagName(jb)[P].appendChild(n)}
com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__startLoadingFragment=function(a){return D(a)};com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(db);d.language=eb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(kb);for(var g=P,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(lb),k;if(j){j=j.replace(mb,X);if(j.indexOf(nb)>=P){continue}if(j==ob){k=i.getAttribute(pb);if(k){var l,m=k.indexOf(qb);if(m>=P){j=k.substring(P,m);l=k.substring(m+Q)}else{j=k;l=X}c[j]=l}}else if(j==rb){k=i.getAttribute(pb);if(k){try{d=eval(k)}catch(a){alert(sb+k+tb)}}}else if(j==ub){k=i.getAttribute(pb);if(k){try{e=eval(k)}catch(a){alert(sb+k+vb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(wb);if(b==-1){b=a.length}var c=a.indexOf(xb);if(c==-1){c=a.length}var d=a.lastIndexOf(yb,Math.min(c,b));return d>=P?a.substring(P,d+Q):X}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(zb);b.src=a+Ab;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Bb);if(a!=null){return a}return X}
function h(){var a=p.getElementsByTagName(db);for(var b=P;b<a.length;++b){if(a[b].src.indexOf(Cb)!=-1){return e(a[b].src)}}return X}
function i(){var a=p.getElementsByTagName(Db);if(a.length>P){return a[a.length-Q].href}return X}
function j(){var a=p.location;return a.href==a.protocol+Eb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==X){k=h()}if(k==X){k=i()}if(k==X&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__moduleBase+a}
function F(){var f=[];var g=P;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
i[Fb]=function(){{var a=o.navigator.userAgent;if(a.indexOf(Gb)==-1&&a.indexOf(Hb)!=-1){return Ib}return Jb}};h[Fb]={'none':P,'yes':Q};__gwt_isKnownPropertyValue=function(a,b){return b in h[a]};com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__computePropValue=j;o.__gwt_activeModules[M].bindings=com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__getPropMap;r(I,Kb);if(q()){return D(Lb)}var k;try{k=Mb;var l=k.indexOf(Nb);if(l!=-1){g=parseInt(k.substring(l+Q),_);k=k.substring(P,l)}}catch(a){}com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__softPermutationId=g;return D(k+Ob)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Pb,J);r(Pb,Qb)}
B();com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__moduleBase=C();t[M].moduleBase=com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.__moduleBase;var H=F();G();r(I,Qb);A(H);return true}
com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset.succeeded=com_sibvisions_rad_ui_vaadin_ext_ui_Widgetset();