-- Copyright 2009 SIB Visions GmbH
--
-- Licensed under the Apache License, Version 2.0 (the "License"); you may not
-- use this file except in compliance with the License. You may obtain a copy of
-- the License at
-- 
-- http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
-- WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
-- License for the specific language governing permissions and limitations under
-- the License.


CREATE TABLE `contacts` (
  `id` int(6) unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(255) DEFAULT NULL,
  `vorname` varchar(255) DEFAULT NULL,
  `nachname` varchar(255) DEFAULT NULL,
  `update_zeit` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
)

CREATE TABLE `TEST_DEFAULTS` (
  `active` char(1) NOT NULL DEFAULT 'N',
  `datetimeval` timestamp NULL DEFAULT '2010-01-01 12:00:00',
  `numberval` int(11) DEFAULT '1234',
  `text` varchar(50) DEFAULT 'TEXT Test',
  `dateval` date DEFAULT '2001-01-01'
) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE `TEST` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE `TEST_SORT` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `SORT` int(10),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE `detail` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `TEST_ID` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_detail_1` (`TEST_ID`),
  CONSTRAINT `FK_detail_1` FOREIGN KEY (`TEST_ID`) REFERENCES `test` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE `deletetest` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE `hdr` (
`ID` INT(10) NOT NULL AUTO_INCREMENT,
`COMP_CODE` INT(10) NOT NULL DEFAULT '0',
`ACCT_YEAR` SMALLINT(5) NOT NULL DEFAULT '0',
`TRN_TYPE` VARCHAR(25) NOT NULL DEFAULT '',
`DOC_NO` VARCHAR(25) NOT NULL DEFAULT '',
`TRN_DT` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
`PARTY` INT(10) NOT NULL DEFAULT '0',
`DOCTOR` INT(10) NULL DEFAULT NULL,
`TOT_TAX` DOUBLE(15,5) NULL DEFAULT NULL,
`AMT_WO_TAX` DOUBLE(15,5) NULL DEFAULT NULL,
`AMOUNT` DOUBLE(15,5) NULL DEFAULT NULL,
`DISC` DOUBLE(15,5) NULL DEFAULT NULL,
`SP_DISC` DOUBLE(15,5) NULL DEFAULT NULL,
`ADJUSTMENT` DOUBLE(15,5) NULL DEFAULT NULL,
`C_NOTE` DOUBLE(15,5) NULL DEFAULT NULL,
`NET_AMOUNT` DOUBLE(15,5) NULL DEFAULT NULL,
`AMOUNT_PAID` DOUBLE(15,5) NULL DEFAULT NULL,
`AMOUN_DUE` DOUBLE(15,5) NULL DEFAULT NULL,
`NARRATION` LONGTEXT NULL,
`PAYMENT_DISC` DOUBLE(15,5) NULL DEFAULT NULL,
`P_DOC_NO` INT(10) NULL DEFAULT NULL,
`P_DT` DATETIME NULL DEFAULT NULL,
`STOCK` TINYINT(1) NULL DEFAULT NULL,
`TAXONFQTY` DOUBLE(15,5) NULL DEFAULT NULL,
PRIMARY KEY (`ID`)
)
ENGINE=InnoDB
ROW_FORMAT=DEFAULT

CREATE TABLE `inventry` (
`ID` INT(10) NOT NULL AUTO_INCREMENT,
`COMP_CODE` INT(10) NULL DEFAULT NULL,
`ACCT_YEAR` SMALLINT(5) NULL DEFAULT NULL,
`TRN_TYPE` VARCHAR(10) NULL DEFAULT NULL,
`DOC_NO` VARCHAR(15) NULL DEFAULT NULL,
`TRN_DT` DATETIME NULL DEFAULT NULL,
`PARTY` INT(10) NULL DEFAULT NULL,
`ITEM_CODE` INT(10) NULL DEFAULT NULL,
`BATCH` VARCHAR(10) NULL DEFAULT NULL,
`EXP` INT(10) NULL DEFAULT NULL,
`QTY_S` INT(10) NULL DEFAULT NULL,
`QTY_P` INT(10) NULL DEFAULT NULL,
`PCS_PER_PACK` SMALLINT(5) NULL DEFAULT NULL,
`PCS_PAID_FOR` SMALLINT(5) NULL DEFAULT NULL,
`RATE` DOUBLE(15,5) NULL DEFAULT NULL,
`MRP` DOUBLE(15,5) NULL DEFAULT NULL,
`PTR` DOUBLE(15,5) NULL DEFAULT NULL,
`PTRPERPCS` DOUBLE(15,5) NULL DEFAULT NULL,
`TAX` DOUBLE(7,2) NULL DEFAULT NULL,
`TAX_AMT` DOUBLE(15,5) NULL DEFAULT NULL,
`ED` DOUBLE(15,5) NULL DEFAULT NULL,
`DISC` DOUBLE(15,5) NULL DEFAULT NULL,
`AMT_WO_TAX` DOUBLE(15,5) NULL DEFAULT NULL,
`AMT` DOUBLE(15,5) NULL DEFAULT NULL,
`FREE_AMT` DOUBLE(15,5) NULL DEFAULT NULL,
`FREE_QTY` DOUBLE(15,5) NULL DEFAULT NULL,
`MULT` SMALLINT(5) NULL DEFAULT NULL,
`MRP_PER_PCS` DOUBLE(15,5) NULL DEFAULT NULL,
`Schd` VARCHAR(3) NULL DEFAULT NULL,
`p_date` DATETIME NULL DEFAULT NULL,
`p_time` DATETIME NULL DEFAULT NULL,
`sale_q` INT(10) NULL DEFAULT NULL,
`profit_per` DOUBLE(15,5) NULL DEFAULT NULL,
`stock` TINYINT(1) NULL DEFAULT NULL,
`WBST` DOUBLE(7,2) NULL DEFAULT NULL,
`HDR_ID` INT(10) NULL DEFAULT NULL,
PRIMARY KEY (`ID`),
INDEX `FK_inventry_items` (`ITEM_CODE`),
INDEX `HDR_ID` (`HDR_ID`),
CONSTRAINT `FK_inventry_items` FOREIGN KEY (`ITEM_CODE`) REFERENCES `hdr` (`ID`)
)
ENGINE=InnoDB
ROW_FORMAT=DEFAULT

CREATE TABLE PERSON (
	id INT(11) NOT NULL AUTO_INCREMENT,
	active ENUM('Y','N') NULL DEFAULT 'y',
	weekdays SET('Mon','Tue','Wed','Thu','Fri','Sat','Sun') NULL DEFAULT NULL,
	PRIMARY KEY (id)
)
ENGINE=InnoDB
ROW_FORMAT=DEFAULT

insert into PERSON (active, weekdays) values ('Y', 'Mon');
insert into PERSON (active, weekdays) values ('N', 'Mon,Fri');

CREATE TABLE ADRESSEN
(
  ID int(18) NOT NULL AUTO_INCREMENT,
  POST_ID int(18) NOT NULL,
  STRA_ID int(18) NOT NULL,
  HAUSNUMMER int(18) NOT NULL,
  TUERNUMMER int(18),
  STIEGE int(18),
  CONSTRAINT ADRESSEN_PK PRIMARY KEY (ID)
);