TYPE=VIEW
query=select `test`.`inventry`.`ID` AS `ID`,`test`.`inventry`.`COMP_CODE` AS `COMP_CODE`,`test`.`inventry`.`ACCT_YEAR` AS `ACCT_YEAR`,`test`.`inventry`.`TRN_TYPE` AS `TRN_TYPE`,`test`.`inventry`.`DOC_NO` AS `DOC_NO`,`test`.`inventry`.`TRN_DT` AS `TRN_DT`,`test`.`inventry`.`PARTY` AS `PARTY`,`test`.`inventry`.`ITEM_CODE` AS `ITEM_CODE`,`test`.`inventry`.`BATCH` AS `BATCH`,`test`.`inventry`.`EXP` AS `EXP`,`test`.`inventry`.`QTY_S` AS `QTY_S`,`test`.`inventry`.`QTY_P` AS `QTY_P`,`test`.`inventry`.`PCS_PER_PACK` AS `PCS_PER_PACK`,`test`.`inventry`.`PCS_PAID_FOR` AS `PCS_PAID_FOR`,`test`.`inventry`.`RATE` AS `RATE`,`test`.`inventry`.`MRP` AS `MRP`,`test`.`inventry`.`PTR` AS `PTR`,`test`.`inventry`.`PTRPERPCS` AS `PTRPERPCS`,`test`.`inventry`.`TAX` AS `TAX`,`test`.`inventry`.`TAX_AMT` AS `TAX_AMT`,`test`.`inventry`.`ED` AS `ED`,`test`.`inventry`.`DISC` AS `DISC`,`test`.`inventry`.`AMT_WO_TAX` AS `AMT_WO_TAX`,`test`.`inventry`.`AMT` AS `AMT`,`test`.`inventry`.`FREE_AMT` AS `FREE_AMT`,`test`.`inventry`.`FREE_QTY` AS `FREE_QTY`,`test`.`inventry`.`MULT` AS `MULT`,`test`.`inventry`.`MRP_PER_PCS` AS `MRP_PER_PCS`,`test`.`inventry`.`Schd` AS `Schd`,`test`.`inventry`.`p_date` AS `p_date`,`test`.`inventry`.`p_time` AS `p_time`,`test`.`inventry`.`sale_q` AS `sale_q`,`test`.`inventry`.`profit_per` AS `profit_per`,`test`.`inventry`.`stock` AS `stock`,`test`.`inventry`.`WBST` AS `WBST`,`test`.`inventry`.`HDR_ID` AS `HDR_ID`,`test`.`items`.`DESCRIPTION` AS `DESCRIPTION` from (`test`.`inventry` left join `test`.`items` on((`test`.`inventry`.`ITEM_CODE` = `test`.`items`.`ID`)))
md5=5ae6560a3f193f63f17291a7a43a05c1
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2010-06-13 17:54:59
create-version=1
source=select `test`.`inventry`.`ID` AS `ID`,`test`.`inventry`.`COMP_CODE` AS `COMP_CODE`,`test`.`inventry`.`ACCT_YEAR` AS `ACCT_YEAR`,`test`.`inventry`.`TRN_TYPE` AS `TRN_TYPE`,`test`.`inventry`.`DOC_NO` AS `DOC_NO`,`test`.`inventry`.`TRN_DT` AS `TRN_DT`,`test`.`inventry`.`PARTY` AS `PARTY`,`test`.`inventry`.`ITEM_CODE` AS `ITEM_CODE`,`test`.`inventry`.`BATCH` AS `BATCH`,`test`.`inventry`.`EXP` AS `EXP`,`test`.`inventry`.`QTY_S` AS `QTY_S`,`test`.`inventry`.`QTY_P` AS `QTY_P`,`test`.`inventry`.`PCS_PER_PACK` AS `PCS_PER_PACK`,`test`.`inventry`.`PCS_PAID_FOR` AS `PCS_PAID_FOR`,`test`.`inventry`.`RATE` AS `RATE`,`test`.`inventry`.`MRP` AS `MRP`,`test`.`inventry`.`PTR` AS `PTR`,`test`.`inventry`.`PTRPERPCS` AS `PTRPERPCS`,`test`.`inventry`.`TAX` AS `TAX`,`test`.`inventry`.`TAX_AMT` AS `TAX_AMT`,`test`.`inventry`.`ED` AS `ED`,`test`.`inventry`.`DISC` AS `DISC`,`test`.`inventry`.`AMT_WO_TAX` AS `AMT_WO_TAX`,`test`.`inventry`.`AMT` AS `AMT`,`test`.`inventry`.`FREE_AMT` AS `FREE_AMT`,`test`.`inventry`.`FREE_QTY` AS `FREE_QTY`,`test`.`inventry`.`MULT` AS `MULT`,`test`.`inventry`.`MRP_PER_PCS` AS `MRP_PER_PCS`,`test`.`inventry`.`Schd` AS `Schd`,`test`.`inventry`.`p_date` AS `p_date`,`test`.`inventry`.`p_time` AS `p_time`,`test`.`inventry`.`sale_q` AS `sale_q`,`test`.`inventry`.`profit_per` AS `profit_per`,`test`.`inventry`.`stock` AS `stock`,`test`.`inventry`.`WBST` AS `WBST`,`test`.`inventry`.`HDR_ID` AS `HDR_ID`,`test`.`items`.`DESCRIPTION` AS `DESCRIPTION` from (`test`.`inventry` left join `test`.`items` on((`test`.`inventry`.`ITEM_CODE` = `test`.`items`.`ID`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `test`.`inventry`.`ID` AS `ID`,`test`.`inventry`.`COMP_CODE` AS `COMP_CODE`,`test`.`inventry`.`ACCT_YEAR` AS `ACCT_YEAR`,`test`.`inventry`.`TRN_TYPE` AS `TRN_TYPE`,`test`.`inventry`.`DOC_NO` AS `DOC_NO`,`test`.`inventry`.`TRN_DT` AS `TRN_DT`,`test`.`inventry`.`PARTY` AS `PARTY`,`test`.`inventry`.`ITEM_CODE` AS `ITEM_CODE`,`test`.`inventry`.`BATCH` AS `BATCH`,`test`.`inventry`.`EXP` AS `EXP`,`test`.`inventry`.`QTY_S` AS `QTY_S`,`test`.`inventry`.`QTY_P` AS `QTY_P`,`test`.`inventry`.`PCS_PER_PACK` AS `PCS_PER_PACK`,`test`.`inventry`.`PCS_PAID_FOR` AS `PCS_PAID_FOR`,`test`.`inventry`.`RATE` AS `RATE`,`test`.`inventry`.`MRP` AS `MRP`,`test`.`inventry`.`PTR` AS `PTR`,`test`.`inventry`.`PTRPERPCS` AS `PTRPERPCS`,`test`.`inventry`.`TAX` AS `TAX`,`test`.`inventry`.`TAX_AMT` AS `TAX_AMT`,`test`.`inventry`.`ED` AS `ED`,`test`.`inventry`.`DISC` AS `DISC`,`test`.`inventry`.`AMT_WO_TAX` AS `AMT_WO_TAX`,`test`.`inventry`.`AMT` AS `AMT`,`test`.`inventry`.`FREE_AMT` AS `FREE_AMT`,`test`.`inventry`.`FREE_QTY` AS `FREE_QTY`,`test`.`inventry`.`MULT` AS `MULT`,`test`.`inventry`.`MRP_PER_PCS` AS `MRP_PER_PCS`,`test`.`inventry`.`Schd` AS `Schd`,`test`.`inventry`.`p_date` AS `p_date`,`test`.`inventry`.`p_time` AS `p_time`,`test`.`inventry`.`sale_q` AS `sale_q`,`test`.`inventry`.`profit_per` AS `profit_per`,`test`.`inventry`.`stock` AS `stock`,`test`.`inventry`.`WBST` AS `WBST`,`test`.`inventry`.`HDR_ID` AS `HDR_ID`,`test`.`items`.`DESCRIPTION` AS `DESCRIPTION` from (`test`.`inventry` left join `test`.`items` on((`test`.`inventry`.`ITEM_CODE` = `test`.`items`.`ID`)))
